from datetime import datetime


ACTION_LOG_SCHEMA = {
    "_id": "ObjectId (auto-generated by MongoDB)",
    "detection_id": "ObjectId/string",
    "action_taken": "string",
    "created_at": datetime,
}
