from datetime import datetime
from typing import Any, Optional


ASSET_SCHEMA = {
    "_id": "ObjectId (auto-generated by MongoDB)",
    "owner": "string",
    "metadata": Optional[dict[str, Any]],
    "created_at": datetime,
}
