from datetime import datetime


DETECTION_SCHEMA = {
    "_id": "ObjectId (auto-generated by MongoDB)",
    "url": "string",
    "similarity_score": "float",
    "platform": "string",
    "timestamp": datetime,
    "matched_asset_id": "ObjectId/string",
}
