from datetime import datetime


FEEDBACK_SCHEMA = {
    "_id": "ObjectId (auto-generated by MongoDB)",
    "detection_id": "ObjectId/string",
    "user_decision": "string",
    "correction": "string | null",
    "created_at": datetime,
}
