from datetime import datetime


FINGERPRINT_SCHEMA = {
    "_id": "ObjectId (auto-generated by MongoDB)",
    "asset_id": "ObjectId/string",
    "hash": "string",
    "embedding": list[float],
    "created_at": datetime,
}
